# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Story:
  fields:
    form: title, edition, column, content_for_edit
    list: title, edition, column
    options:
      selectors: column
      templates:
        content_for_edit: text
  order_by: -edition, column
  search: title, edition
  application: Pickard Ayune

